[package]
name = "battery-estimator"
version = "0.1.6"
edition = "2021"
rust-version = "1.82"
description = "A no_std, zero-dependency library for estimating battery SOC from voltage"
readme = "README.md"
repository = "https://github.com/KingingWang/battery-estimator"
license = "MIT"
keywords = ["battery", "soc", "no-std", "voltage", "level"]
categories = ["embedded", "no-std"]
authors = ["kingingwang@foxmail.com"]

[dependencies]
thiserror = { version = "2", default-features = false }

[features]
default = []
